<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="ExceptionDispatchInfo.xml" source-language="en-US" target-language="zh-CN">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac5c9705c7cab056ffd2d3a6a05962a03c0ae933d19.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">c9705c7cab056ffd2d3a6a05962a03c0ae933d19</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netcore-1.0,netcore-1.1,netcore-2.0,netcore-2.1,netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,netstandard-1.0,netstandard-1.1,netstandard-1.2,netstandard-1.3,netstandard-1.4,netstandard-1.5,netstandard-1.6,netstandard-2.0,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo">
          <source>Represents an exception whose state is captured at a certain point in code.</source>
          <target state="translated">表示在代码中的某个特定点捕获其状态的异常。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo">
          <source>The <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph> object stores the stack trace information and Watson information that the exception contains at the point where it is captured.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph>对象存储的堆栈跟踪信息和该异常包含捕获时的点处的 Watson 信息。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo">
          <source>The exception can be thrown at another time and possibly on another thread by calling the <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A?displayProperty=nameWithType&gt;</ph> method.</source>
          <target state="translated">可能会引发异常可能在其他时间和另一个线程通过调用<ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A?displayProperty=nameWithType&gt;</ph>方法。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo">
          <source>The exception is thrown as if it had flowed from the point where it was captured to the point where the <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A&gt;</ph> method is called.</source>
          <target state="translated">就像它已从已捕获到点处的点流入引发异常其中<ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A&gt;</ph>调用方法。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo">
          <source><ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph> cannot be serialized and is not intended to cross application domain boundaries.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph> 无法序列化和不能跨应用程序域边界。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>The exception whose state is captured, and which is represented by the returned object.</source>
          <target state="translated">由一个返回的对象表示且状态被捕获的异常。</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>Creates an <ph id="ph1">&lt;see cref="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo" /&gt;</ph> object that represents the specified exception at the current point in code.</source>
          <target state="translated">创建 <ph id="ph1">&lt;see cref="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo" /&gt;</ph> 对象，此对象在代码当前点表示指定异常。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>An object that represents the specified exception at the current point in code.</source>
          <target state="translated">表示代码中当前点的指定异常的对象。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>You can use the <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph> object that is returned by this method at another time and possibly on another thread to rethrow the specified exception, as if the exception had flowed from this point where it was captured to the point where it is rethrown.</source>
          <target state="translated">你可以使用<ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph>返回此方法在其他时间并尽可能在另一个线程重新引发指定的异常，如如果异常已流入，则从该点已捕获到它将被重新引发的点处的对象。</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>If the exception is active when it is captured, the current stack trace information and Watson information that is contained in the exception is stored.</source>
          <target state="translated">如果异常处于活动状态时捕获时，当前的堆栈跟踪信息并且包含在中的 Watson 信息将存储异常。</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>If it is inactive, that is, if it has not been thrown, it will not have any stack trace information or Watson information.</source>
          <target state="translated">如果它处于非活动状态，也就是说，如果它不引发，它将不具有任何堆栈跟踪信息或 Watson 的信息。</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source><ph id="ph1">&lt;paramref name="source" /&gt;</ph> is <ph id="ph2">&lt;see langword="null" /&gt;</ph>.</source>
          <target state="translated"><ph id="ph1">&lt;paramref name="source" /&gt;</ph> 为 <ph id="ph2">&lt;see langword="null" /&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="P:System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException">
          <source>Gets the exception that is represented by the current instance.</source>
          <target state="translated">获取被当前实例表示的异常。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException">
          <source>The exception that is represented by the current instance.</source>
          <target state="translated">被当前实例表示的异常。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException">
          <source>This property is used by the Task Parallel Library, for example, to combine multiple exceptions in an <ph id="ph1">&lt;xref:System.AggregateException&gt;</ph> object.</source>
          <target state="translated">使用此属性是任务并行库中，例如，组合中的多个异常<ph id="ph1">&lt;xref:System.AggregateException&gt;</ph>对象。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException">
          <source>It is not intended to be used by application code.</source>
          <target state="translated">它不是由应用程序代码使用。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException">
          <source>Use the <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A&gt;</ph> method to restore the state of the captured exception and throw it.</source>
          <target state="translated">使用<ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A&gt;</ph>还原捕获的异常状态并引发它的方法。</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw">
          <source>Throws the exception that is represented by the current <ph id="ph1">&lt;see cref="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo" /&gt;</ph> object, after restoring the state that was saved when the exception was captured.</source>
          <target state="translated">恢复捕获异常时保存的状态后，引发由当前 <ph id="ph1">&lt;see cref="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo" /&gt;</ph> 对象表示的异常。</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw">
          <source>When the exception is restored, the following string is inserted in the stack trace to indicate the restore point: "End of stack trace from the previous location where the exception was thrown".</source>
          <target state="translated">当恢复异常时，在堆栈跟踪以指示还原点中插入以下字符串:"末尾之前的位置引发异常的堆栈跟踪"。</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw">
          <source>This is similar to the way inner exceptions or marshaled exceptions are indicated in stack traces.</source>
          <target state="translated">这是内部的异常或已封送的异常指示在堆栈跟踪中的工作方式相似。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>